// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bsrnfgj10ApQBT6_7s8S1V9hExy5ARA',
    appId: '1:649477813882:web:b29e32505b5f28c3eaedc3',
    messagingSenderId: '649477813882',
    projectId: 'laporan-keuangan-da8d7',
    authDomain: 'laporan-keuangan-da8d7.firebaseapp.com',
    storageBucket: 'laporan-keuangan-da8d7.appspot.com',
    measurementId: 'G-324X3SV0GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHDzq1hFPdUvICBi6CAA-bI_pxQpDm14',
    appId: '1:649477813882:android:42d5e4f1ccd3c1a7eaedc3',
    messagingSenderId: '649477813882',
    projectId: 'laporan-keuangan-da8d7',
    storageBucket: 'laporan-keuangan-da8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0KcQsOqvu772MjPUoVXhPy32p6CufJFI',
    appId: '1:649477813882:ios:84ed31bfb42b47c3eaedc3',
    messagingSenderId: '649477813882',
    projectId: 'laporan-keuangan-da8d7',
    storageBucket: 'laporan-keuangan-da8d7.appspot.com',
    iosBundleId: 'com.example.keuanganFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0KcQsOqvu772MjPUoVXhPy32p6CufJFI',
    appId: '1:649477813882:ios:cffc098006c92fdeeaedc3',
    messagingSenderId: '649477813882',
    projectId: 'laporan-keuangan-da8d7',
    storageBucket: 'laporan-keuangan-da8d7.appspot.com',
    iosBundleId: 'com.example.keuanganFirebase.RunnerTests',
  );
}
